# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{user_stack}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Neighman"]
  s.date = %q{2009-12-07}
  s.email = %q{has.sox@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/user_stack.rb",
     "lib/user_stack/config.ru",
     "lib/user_stack/config/config.rb",
     "lib/user_stack/config/environments/development.rb",
     "lib/user_stack/config/environments/production.rb",
     "lib/user_stack/config/environments/staging.rb",
     "lib/user_stack/config/router.rb",
     "lib/user_stack/lib/password.rb",
     "lib/user_stack/master/config/config.rb",
     "lib/user_stack/master/db/development.db",
     "lib/user_stack/tasks/user_stack.rake",
     "lib/user_stack/user_models/data_mapper/user.rb",
     "lib/user_stack/user_models/mongo_mapper/user.rb",
     "lib/user_stack/user_stack.rb",
     "lib/user_stack/views/new.html.haml",
     "lib/user_stack/views/show.html.haml",
     "spec/spec_helper.rb",
     "spec/user_stack_spec.rb"
  ]
  s.homepage = %q{http://github.com/hassox/user_stack}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Stack that provides basic User management}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/user_stack_spec.rb",
     "test/helper.rb",
     "test/test_user_stack.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<pancake>, [">= 0.1.28"])
      s.add_runtime_dependency(%q<veneer>, [">= 0.1.3"])
    else
      s.add_dependency(%q<pancake>, [">= 0.1.28"])
      s.add_dependency(%q<veneer>, [">= 0.1.3"])
    end
  else
    s.add_dependency(%q<pancake>, [">= 0.1.28"])
    s.add_dependency(%q<veneer>, [">= 0.1.3"])
  end
end

